language: go
branches:
  only:
    - master

go: 1.10.x

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get -u golang.org/x/lint/golint

script:
  - ./verify.sh

deploy:
  - provider: script
    script:
    - ./deploy.sh
                  
