apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: rgwpubsub-source
spec:
  hosts:
  - "<rgw endpoint>"
  - "vision.googleapis.com" # to access google vision
  ports:
  - number: 80 #rgw pubsub port
    name: http
    protocol: HTTP
  - number: 8080 #rgw port
    name: rgw
    protocol: HTTP
  - number: 443 # https, to access google vision endpoint
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
